# ==========================================
# Server config
# ==========================================
server.port=8080

# ==========================================
# Database connection pool config
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/snickr_db
spring.datasource.username=postgres
spring.datasource.password=snickr123
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP connection pool settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# ==========================================
# Initialize database
# ==========================================
spring.sql.init.mode=always

# Create table script
spring.sql.init.schema-locations=classpath:01_schema.sql

# Add sample data
# spring.sql.init.data-locations=classpath:03_sample_data.sql

# ==========================================
# Thymeleaf config
# ==========================================
spring.thymeleaf.cache=false